# Generated by Django 5.2.1 on 2025-05-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='cpf',
        ),
        migrations.AddField(
            model_name='paciente',
            name='cpf_criptografado',
            field=models.CharField(default='vazio', max_length=255),
            preserve_default=False,
        ),
    ]
